---
- name: Setting Location of Inventory Directory
  set_fact:
    inventory_dir: "{{ inventory.path | realpath }}"
- name: Include Inventory
  include_vars:
    dir: "{{ inventory_dir }}/group_vars"
- name: OpenShift Applier Role
  include_role:
    name: "{{ (playbook_dir ~ '/../../roles/openshift-applier') | realpath }}"
