---

- name: "Determine location for the 'file'"
  vars:
    path: "{{ file }}"
  import_tasks: check-file-location.yml

- name: "{{ oc_action | capitalize }} OpenShift objects based on static files for '{{ entry.object}} : {{ content.name | default(file | basename) }}'"
  command: >
    oc {{ oc_action }} \
       {{ oc_target_namespace }} \
       -f {{ oc_file_path }} \
       {{ (oc_action == 'delete') | ternary(' --ignore-not-found', '') }}
  register: command_result
  failed_when:
  - command_result.rc != 0
  - "'AlreadyExists' not in command_result.stderr"
