---

###############################
# OpenShift Pre-Requisites

# - subscribe hosts
# - prepare docker
# - other prep (install additional packages, etc.)
#
- hosts: OSEv3
  roles:
    - { role: openshift-ansible-contrib/roles/subscription-manager, when: hostvars.localhost.rhsm_register, tags: 'subscription-manager', ansible_sudo: true }
    - { role: openshift-ansible-contrib/roles/docker, tags: 'docker' }
    - { role: openshift-ansible-contrib/roles/openshift-prep, tags: 'openshift-prep' }

